spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EMPLOYEE_DB
    username: root
    password: root1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
